export enum FontFamily {
  PoppinsBlack = 'Poppins-Black',
  PoppinsBlackItalic = 'Poppins-BlackItalic',
  PoppinsBold = 'Poppins-Bold',
  PoppinsBoldItalic = 'Poppins-BoldItalic',
  PoppinsExtraBold = 'Poppins-ExtraBold',
  PoppinsExtraBoldItalic = 'Poppins-ExtraBoldItalic',
  PoppinsExtraLight = 'Poppins-ExtraLight',
  PoppinsExtraLightItalic = 'Poppins-ExtraLightItalic',
  PoppinsItalic = 'Poppins-Italic',
  PoppinsLight = 'Poppins-Light',
  PoppinsLightItalic = 'Poppins-LightItalic',
  PoppinsMedium = 'Poppins-Medium',
  PoppinsMediumItalic = 'Poppins-MediumItalic',
  PoppinsRegular = 'Poppins-Regular',
  PoppinsSemiBold = 'Poppins-SemiBold',
  PoppinsSemiBoldItalic = 'Poppins-SemiBoldItalic',
  PoppinsThin = 'Poppins-Thin',
  PoppinsThinItalic = 'Poppins-ThinItalic',
}

export enum FontSize {
  FS_10 = 10,
  FS_11 = 11,
  FS_12 = 12,
  FS_13 = 13,
  FS_14 = 14,
  FS_15 = 15,
  FS_16 = 16,
  FS_17 = 17,
  FS_18 = 18,
  FS_19 = 19,
  FS_20 = 20,
  FS_21 = 21,
  FS_22 = 22,
  FS_23 = 23,
  FS_24 = 24,
  FS_25 = 25,
  FS_26 = 26,
  FS_27 = 27,
  FS_28 = 28,
  FS_29 = 29,
  FS_30 = 30,
  FS_31 = 31,
  FS_32 = 32,
  FS_33 = 33,
  FS_34 = 34,
  FS_35 = 35,
}

export enum todoListButtons {
  Delete = 1,
  Done = 2,
}
